Feature/mobile banner
FoodKlore/Landing pull request #15
Opened 2020-02-24 02:34 UTC by aalejandromr

2020-03-02 03:12 UTC, eduarmreyes approved these changes
looks good

2020-03-02 03:13 UTC, eduarmreyes requested changes
Sólo revisa que los botones sean del mismo tamaño

2020-03-03 03:46 UTC, eduarmreyes requested changes
por fa cambia `span` por `Link` o `a`

2020-03-03 03:46 UTC, eduarmreyes commented on src/components/navigation.js
> +        <span  onClick={() => scrollTo("#home")} >Home</span>
uy, ¿por qué `span`? Debería ser en todo caso `Link` o `a`

2020-03-03 03:48 UTC, aalejandromr commented on src/components/navigation.js
> +        <span  onClick={() => scrollTo("#home")} >Home</span>
Por que `smooth-scroll` plugin tiene problemas con links

2020-03-03 07:03 UTC, eduarmreyes commented on src/components/navigation.js
> +        <span  onClick={() => scrollTo("#home")} >Home</span>
no me convence, voy a ver qué ondas en local

2020-03-03 07:19 UTC, eduarmreyes commented on src/components/navigation.js
> +        <span  onClick={() => scrollTo("#home")} >Home</span>
lo resolví

2020-03-04 04:52 UTC, eduarmreyes approved these changes
good job, thanks

2020-03-04 04:52 UTC, merged