Fix gatsby dependency and remove scroll package
FoodKlore/Landing pull request #17
Opened 2020-03-04 06:03 UTC by eduarmreyes

2020-03-05 01:50 UTC, aalejandromr commented
This doesn't work on safari, the smooth plugin you are removing does.

2020-03-08 03:55 UTC, eduarmreyes commented
> This doesn't work on safari, the smooth plugin you are removing does.

qué hueva instalar un paquete para esa funcionalidad, 😩, igual lo hice y está funcionando

2020-03-09 02:44 UTC, aalejandromr approved these changes

2020-03-09 02:45 UTC, aalejandromr requested changes
Just fix conflicts

2020-03-09 03:03 UTC, aalejandromr approved these changes

2020-03-09 03:04 UTC, aalejandromr approved these changes

2020-03-09 03:05 UTC, merged