Feature/showcase
FoodKlore/Landing pull request #4
Opened 2020-01-14 05:01 UTC by aalejandromr

![image](https://user-images.githubusercontent.com/19537074/72315524-0f9e9480-3661-11ea-97cb-899781bf1728.png)

2020-01-14 15:47 UTC, emejia-mdsol commented on src/components/bannerImage.js
> +  return {
súper bien

2020-01-14 15:47 UTC, emejia-mdsol commented on src/components/global/index.js
> +export { FkH1 as H1, FkP as P, FkH2 as H2, FkH3 as H3, FkDownloadApp }
¿`Fk` es fake?

2020-01-14 15:48 UTC, emejia-mdsol requested changes
preferiría que los componentes tuviera un nombre más fácil de entender y el nombre completo

2020-01-15 00:07 UTC, aalejandromr commented on src/components/global/index.js
> +export { FkH1 as H1, FkP as P, FkH2 as H2, FkH3 as H3, FkDownloadApp }
Fk es por FoodKlore, que te parece la idea para representar componentes propios de la marca? 🤔

2020-01-15 00:08 UTC, aalejandromr commented on src/components/global/index.js
> +export { FkH1 as H1, FkP as P, FkH2 as H2, FkH3 as H3, FkDownloadApp }
pensalo, y si no te gusta la idea, lo cambio a algo mas facil de entender y recordar, experimentando con ideas para representar componentes propios de la marca 😄

2020-01-15 00:22 UTC, eduarmreyes commented on src/components/global/index.js
> +export { FkH1 as H1, FkP as P, FkH2 as H2, FkH3 as H3, FkDownloadApp }
mm no me parece tanto la idea la verdad, he visto componentes intentando hacer esto y fallan porque después cuando más gente se une al equipo no les es fácil entender el contexto de los componentes.

Si querés mucho seguir esta idea yo recomendaria algo como `FoodKloreDownloadButton` o `FoodKloreH3` pero el problema con eso es que, qué hueva estar escribiendo todo ese nombre largo para un componente estilizado

2020-01-15 00:24 UTC, aalejandromr commented on src/components/global/index.js
> +export { FkH1 as H1, FkP as P, FkH2 as H2, FkH3 as H3, FkDownloadApp }
Va, entonces voy a volver a lo normal. ex. `H3`

2020-01-15 01:31 UTC, eduarmreyes approved these changes
lgtm

2020-01-15 01:32 UTC, merged